kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: demo-service2-order
  name: demo-service2-order
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service2-order
  template:
    metadata:
      name: demo-service2-order
      labels:
        app: demo-service2-order
    spec:
      containers:
      - name: demo-service2-order
        image: repository:5000/demo-service2-order
        imagePullPolicy: Always
        env:
          - name: GIT_URL
            value: "http://demo-service-config:9000"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service2-order
  name: demo-service2-order
  namespace: default
spec:
  ports:
  - port: 9005
    targetPort: 9005
  selector:
    app: demo-service2-order
